name: Auto Assign

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  assign:
    runs-on: ubuntu-latest
    steps:
      - uses: hkusu/review-assign-action@v1
        with:
          assignees: ${{ github.actor }} # assign pull request author