name: Auto Assign

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  assign:
    runs-on: ubuntu-latest
    steps:
      # Github actor 값 출력
      - name: Check github.actor value
        run: echo "Actor ${{ github.actor }}"

      - uses: hkusu/review-assign-action@v1
        with:
          assignees: ${{ github.actor }} # assign pull request author